baseURL = "https://xiaosuiba.github.io/"
title = "ChrisLi's Blog"
author = "Chris Li"
paginate = 5
languageCode = "zh-cn"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
theme = "harbor"

[Author]
  name = "Chris Li"

[permalinks]
	post = "/:year/:month/:day/:filename/"
	page = "/:filename/"

[outputs]
    section = ["JSON", "HTML"]

[[params.nav]]
  identifier = "about"
  name = "About"
  icon = "fas fa-user fa-lg"
  url = "/about/"
  weight = 3

[[params.nav]]
  identifier = "tags"
  name = "Tags"
  icon = "fas fa-tag fa-lg"
  url = "/tags/"
  weight = 3

[[params.nav]]
  identifier = "search"
  name = "Search"
  icon = "fas fa-search fa-lg"
  url = "/search/"
  weight = 3

[[params.social]]
  name= "Twitter"
  url="https://twitter.com/xiaosuiba"
  icon="fab fa-twitter"

[[params.social]]
  name= "GitHub"
  url="https://github.com/xiaosuiba"
  icon="fab fa-github"

[params]
  mainSections = ["post"]
  favicon = "favicon.ico"

  [params.logo]
    url = "natsume.jpg"
    width = 50
    height = 50
    alt = "Logo"